config/routes.rb
Loja::Application.routes.draw do
  
  resources :produtos
  resources :itens

  root :to => 'produtos#index'

end

app/models/item.rb
class Item < ActiveRecord::Base

	belongs_to :produto
	belongs_to :pedido


	validates_presence_of :quantidade,
			:pedido_id,
			:produto_id

	validates_numericality_of :quantidade, 
			:integer_only => true,
			:allow_blank => true


	attr_accessible :produto_id, :produto,
			:quantidade


 	def incrementar_quantidade ( quantidade )
 		 self.quantidade += quantidade.to_i
 	end


end

app/models/pedido.rb
class Pedido < ActiveRecord::Base

	has_many :itens


	def adicionar_produto( produto, quantidade )
      if item = self.itens.detect { |i| i.produto == produto }
      	item.incrementar_quantidade(quantidade)
      	item.save!
      else
      	self.itens.create!(
      		:produto => produto,
      		:quantidade => quantidade)
      end

     end 

end

app/models/produto.rb
class Produto < ActiveRecord::Base

	validates_presence_of :nome, :descricao, :preco
	validates_numericality_of :preco, :greater_than => 0, :allow_blank => true
    attr_accessible :nome, :descricao, :preco
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :pedido_atual

  protected

   def pedido_atual
  	 if @pedido_atual.nil? && !session[:pedido_atual_id].nil?
  	 	 @pedido_atual = Pedido.find_by_id( session[:pedido_atual_id] )
  	 end
     @pedido_atual ||= Pedido.new
   end


end

app/controllers/itens_controller.rb
class ItensController < ApplicationController

	def create 

	 if self.pedido_atual.new_record?
	 	self.pedido_atual.save!
	 	session[:pedido_atual_id] = self.pedido_atual.id
	 end
	 

	@produto = Produto.find( params[:produto_id] )
	@quantidade = params[:quantidade]
	self.pedido_atual.adicionar_produto( @produto, @quantidade )

	respond_to do |format|
		format.html do
		  flash[:success] = %Q!O produto #{@produto.nome} 
		    foi adicionado com sucesso no seu carrinho!
		 redirect_to produtos_path
		end
	end   
 end
end

app/controllers/produtos_controller.rb
class ProdutosController <
	ApplicationController

	def index
		@produtos = Produto.all

        respond_to do |format|
          format.html
          format.json { render :json => @produtos }
          format.xml { render :xml => @produtos }
         end 
	end

    def show
    	@produto = Produto.find(params[:id])
    end
    
    def new
    	@produto = Produto.new
    end

    def create
        
    	@produto = Produto.new(params[:produto])
    	 if @produto.save
            flash[:success] = 'O produto foi salvo com sucesso'
    	 	redirect_to produtos_path
    	 else
            flash.now[:error] = 'Ocorreram erros na hora de gravar o produto'
    	 	render :new
    	 end
   	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/compartilhados/_mensagens.html.haml
- [:error, :success, :info].each do |key|
  - unless flash[key].blank?
    %div{ :class => "alert alert-#{key}"}
      %a.close{'data-dismiss' => 'alert', 'href' => '#'}
        x
      = flash[key]

app/views/compartilhados/_navbar.html.erb
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to 'Loja', root_url, :class => 'brand' %>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="">
                <%= link_to 'Produtos', produtos_url %>
              </li>
            </ul>
              <ul class="nav pull-right">
                <li class="divider-vertical"></li>
                <li>
                  <%= link_to 'Carrinho de compras', itens_url %>
                </li>
             
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/compartilhados/_oldmensagens.html.erb
<% [:error, :success, :info].each do |key| %>
 <% unless flash[key].blank? %>
  <div class="alert alert-<%= key %>">
   <a class="close" data-dismiss="alert" href="#">×</a>
   <%= flash[key] %>
  </div>
 <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loja</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'compartilhados/navbar' %>
<%= render 'compartilhados/mensagens' %>
<%= yield %>

</body>
</html>

app/views/produtos/index.html.erb
<h2>
	Lista de Produtos
</h2>

   <p>
     <%= link_to( 'Novo Produto', new_produto_url, :class => 'btn btn-primary' ) %>
     </p>
<table class="table table-bordered table-striped">
 <thead>
  <tr>
  <th>Nome</th>
  <th>Preço</th>
  <th>Quantidade</th>
  </tr>
  </thead>
  <tbody>
   <% @produtos.each do |produto| %>
   	<tr>
   	<td><%= link_to( produto.nome, produto_path(produto) )%></td>
   	<td><%= number_to_currency produto.preco %></td>
   	<td>
     <%= form_tag itens_path, :method => :post do %>
      <%= hidden_field_tag :produto_id, produto.id %>
      <%= text_field_tag :quantidade, 1 %>
      <%= submit_tag 'Adicionar' %>
      <% end %>
      </td>
    </tr>
   	<% end %>
   </tbody>
  </table>

app/views/produtos/new.html.erb
<h2>
	Novo Produto
</h2>

  <%= form_for @produto do |f| %>

    <% unless @produto.errors.blank? %>
      <ul>
        <% @produto.errors.full_messages.each do |erro| %>
        <li> <%= erro %> </li>
        <% end %>
      </ul>
      <% end %>
  	<p>
  		Nome: <%= f.text_field :nome %>
  	</p>

  	<p>
  		Preço: <%= f.text_field :preco %>
  	</p>

  	<p>
  		Descrição: 
  		<br/>
  		<%= f.text_area :descricao %>
  	</p>

  	<p>
  		<%= f.submit 'Enviar' %>
  	</p>

<% end %>

app/views/produtos/show.html.erb
<h1> <%= @produto.nome %> </h1>
<h2> 
	Preço: <%= number_to_currency @produto.preco %>
</h2>

<p> 
	<%= @produto.descricao %>
</p>